name: Apply Domain Template

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  apply-template:
    runs-on: ubuntu-latest
    steps:
      - name: Debug variables and secrets
        run: |
          echo "App ID set: ${{ vars.WORKFLOW_WRITE_APP_ID != '' }}"
          echo "Private key set: ${{ secrets.WORKFLOW_WRITE_APP_PRIVATE_KEY != '' }}"
          
      - name: Get GitHub App Token
        id: app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.WORKFLOW_WRITE_APP_ID }}
          private_key: ${{ secrets.WORKFLOW_WRITE_APP_PRIVATE_KEY }}

      - name: Debug token permissions
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          curl -s -H "Authorization: Bearer $APP_TOKEN" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/AcmeTickets/HumanResources | jq .permissions
          
      - name: Debug token metadata
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          curl -s -H "Authorization: Bearer $APP_TOKEN" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com | jq .

      - name: Debug accessible repositories
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          curl -s -H "Authorization: Bearer $APP_TOKEN" -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/installation/repositories | jq .
